#!/bin/bash

echo "📧 Email Configuration Setup"
echo "============================"
echo ""
echo "I can see you're trying to send emails but getting 'Internal server error'."
echo "This is because the email credentials are not configured."
echo ""
echo "To fix this, you need to:"
echo ""
echo "1. 🔐 Enable 2-Factor Authentication on your Gmail account"
echo "2. 🔑 Generate an App Password"
echo "3. ⚙️ Update the configuration"
echo ""
echo "Step-by-step instructions:"
echo ""
echo "📱 Step 1: Enable 2-Factor Authentication"
echo "   - Go to your Google Account settings"
echo "   - Security → 2-Step Verification"
echo "   - Enable it if not already enabled"
echo ""
echo "🔑 Step 2: Generate App Password"
echo "   - Go to Google Account settings"
echo "   - Security → 2-Step Verification → App passwords"
echo "   - Select 'Mail' and generate a new password"
echo "   - Copy the 16-character password"
echo ""
echo "⚙️ Step 3: Update Configuration"
echo "   - Edit the file: backend/.env"
echo "   - Change these lines:"
echo "     EMAIL_USER=arpitbabu802@gmail.com"
echo "     EMAIL_PASSWORD=your_16_character_app_password"
echo ""
echo "🔄 Step 4: Restart Server"
echo "   - Stop the current server (Ctrl+C)"
echo "   - Run: npm run dev"
echo ""
echo "🧪 Step 5: Test Email"
echo "   - Try sending a test email from the app"
echo "   - Check if you receive the email"
echo ""
echo "Current configuration:"
echo "EMAIL_USER: $(grep EMAIL_USER backend/.env | cut -d'=' -f2)"
echo "EMAIL_PASSWORD: $(grep EMAIL_PASSWORD backend/.env | cut -d'=' -f2)"
echo ""
echo "Would you like me to help you update the configuration once you have your app password?"
